//
// Generated by Bluespec Compiler, version 2022.01-36-ga6304315 (build a6304315)
//
// On Tue Oct  4 10:37:19 CEST 2022
//
//
// Ports:
// Name                         I/O  size props
// slave_awready                  O     1 reg
// slave_wready                   O     1 reg
// slave_bvalid                   O     1 reg
// slave_bresp                    O     2 reg
// slave_arready                  O     1 reg
// slave_rvalid                   O     1 reg
// slave_rresp                    O     2 reg
// slave_rdata                    O    32 reg
// sb_gpio_to_plic_get            O    16 reg
// io_gpio_out                    O    16 reg
// RDY_io_gpio_out                O     1 const
// io_gpio_out_en                 O    16 reg
// RDY_io_gpio_out_en             O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// slave_m_awvalid_awvalid        I     1
// slave_m_awvalid_awaddr         I    32 reg
// slave_m_awvalid_awsize         I     2 reg
// slave_m_awvalid_awprot         I     3 reg
// slave_m_wvalid_wvalid          I     1
// slave_m_wvalid_wdata           I    32 reg
// slave_m_wvalid_wstrb           I     4 reg
// slave_m_bready_bready          I     1
// slave_m_arvalid_arvalid        I     1
// slave_m_arvalid_araddr         I    32 reg
// slave_m_arvalid_arsize         I     2 reg
// slave_m_arvalid_arprot         I     3 reg
// slave_m_rready_rready          I     1
// io_gpio_in_inp                 I    16 reg
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkgpio(CLK,
	      RST_N,

	      slave_m_awvalid_awvalid,
	      slave_m_awvalid_awaddr,
	      slave_m_awvalid_awsize,
	      slave_m_awvalid_awprot,

	      slave_awready,

	      slave_m_wvalid_wvalid,
	      slave_m_wvalid_wdata,
	      slave_m_wvalid_wstrb,

	      slave_wready,

	      slave_bvalid,

	      slave_bresp,

	      slave_m_bready_bready,

	      slave_m_arvalid_arvalid,
	      slave_m_arvalid_araddr,
	      slave_m_arvalid_arsize,
	      slave_m_arvalid_arprot,

	      slave_arready,

	      slave_rvalid,

	      slave_rresp,

	      slave_rdata,

	      slave_m_rready_rready,

	      sb_gpio_to_plic_get,

	      io_gpio_in_inp,

	      io_gpio_out,
	      RDY_io_gpio_out,

	      io_gpio_out_en,
	      RDY_io_gpio_out_en);
  input  CLK;
  input  RST_N;

  // action method slave_m_awvalid
  input  slave_m_awvalid_awvalid;
  input  [31 : 0] slave_m_awvalid_awaddr;
  input  [1 : 0] slave_m_awvalid_awsize;
  input  [2 : 0] slave_m_awvalid_awprot;

  // value method slave_m_awready
  output slave_awready;

  // action method slave_m_wvalid
  input  slave_m_wvalid_wvalid;
  input  [31 : 0] slave_m_wvalid_wdata;
  input  [3 : 0] slave_m_wvalid_wstrb;

  // value method slave_m_wready
  output slave_wready;

  // value method slave_m_bvalid
  output slave_bvalid;

  // value method slave_m_bresp
  output [1 : 0] slave_bresp;

  // value method slave_m_buser

  // action method slave_m_bready
  input  slave_m_bready_bready;

  // action method slave_m_arvalid
  input  slave_m_arvalid_arvalid;
  input  [31 : 0] slave_m_arvalid_araddr;
  input  [1 : 0] slave_m_arvalid_arsize;
  input  [2 : 0] slave_m_arvalid_arprot;

  // value method slave_m_arready
  output slave_arready;

  // value method slave_m_rvalid
  output slave_rvalid;

  // value method slave_m_rresp
  output [1 : 0] slave_rresp;

  // value method slave_m_rdata
  output [31 : 0] slave_rdata;

  // value method slave_m_ruser

  // action method slave_m_rready
  input  slave_m_rready_rready;

  // actionvalue method sb_gpio_to_plic_get
  output [15 : 0] sb_gpio_to_plic_get;

  // action method io_gpio_in
  input  [15 : 0] io_gpio_in_inp;

  // value method io_gpio_out
  output [15 : 0] io_gpio_out;
  output RDY_io_gpio_out;

  // value method io_gpio_out_en
  output [15 : 0] io_gpio_out_en;
  output RDY_io_gpio_out_en;

  // signals for module outputs
  wire [31 : 0] slave_rdata;
  wire [15 : 0] io_gpio_out, io_gpio_out_en, sb_gpio_to_plic_get;
  wire [1 : 0] slave_bresp, slave_rresp;
  wire RDY_io_gpio_out,
       RDY_io_gpio_out_en,
       slave_arready,
       slave_awready,
       slave_bvalid,
       slave_rvalid,
       slave_wready;

  // register gpio_datain_register_0
  reg gpio_datain_register_0;
  wire gpio_datain_register_0_D_IN, gpio_datain_register_0_EN;

  // register gpio_datain_register_1
  reg gpio_datain_register_1;
  wire gpio_datain_register_1_D_IN, gpio_datain_register_1_EN;

  // register gpio_datain_register_10
  reg gpio_datain_register_10;
  wire gpio_datain_register_10_D_IN, gpio_datain_register_10_EN;

  // register gpio_datain_register_11
  reg gpio_datain_register_11;
  wire gpio_datain_register_11_D_IN, gpio_datain_register_11_EN;

  // register gpio_datain_register_12
  reg gpio_datain_register_12;
  wire gpio_datain_register_12_D_IN, gpio_datain_register_12_EN;

  // register gpio_datain_register_13
  reg gpio_datain_register_13;
  wire gpio_datain_register_13_D_IN, gpio_datain_register_13_EN;

  // register gpio_datain_register_14
  reg gpio_datain_register_14;
  wire gpio_datain_register_14_D_IN, gpio_datain_register_14_EN;

  // register gpio_datain_register_15
  reg gpio_datain_register_15;
  wire gpio_datain_register_15_D_IN, gpio_datain_register_15_EN;

  // register gpio_datain_register_2
  reg gpio_datain_register_2;
  wire gpio_datain_register_2_D_IN, gpio_datain_register_2_EN;

  // register gpio_datain_register_3
  reg gpio_datain_register_3;
  wire gpio_datain_register_3_D_IN, gpio_datain_register_3_EN;

  // register gpio_datain_register_4
  reg gpio_datain_register_4;
  wire gpio_datain_register_4_D_IN, gpio_datain_register_4_EN;

  // register gpio_datain_register_5
  reg gpio_datain_register_5;
  wire gpio_datain_register_5_D_IN, gpio_datain_register_5_EN;

  // register gpio_datain_register_6
  reg gpio_datain_register_6;
  wire gpio_datain_register_6_D_IN, gpio_datain_register_6_EN;

  // register gpio_datain_register_7
  reg gpio_datain_register_7;
  wire gpio_datain_register_7_D_IN, gpio_datain_register_7_EN;

  // register gpio_datain_register_8
  reg gpio_datain_register_8;
  wire gpio_datain_register_8_D_IN, gpio_datain_register_8_EN;

  // register gpio_datain_register_9
  reg gpio_datain_register_9;
  wire gpio_datain_register_9_D_IN, gpio_datain_register_9_EN;

  // register gpio_dataout_register_0
  reg gpio_dataout_register_0;
  wire gpio_dataout_register_0_D_IN, gpio_dataout_register_0_EN;

  // register gpio_dataout_register_1
  reg gpio_dataout_register_1;
  wire gpio_dataout_register_1_D_IN, gpio_dataout_register_1_EN;

  // register gpio_dataout_register_10
  reg gpio_dataout_register_10;
  wire gpio_dataout_register_10_D_IN, gpio_dataout_register_10_EN;

  // register gpio_dataout_register_11
  reg gpio_dataout_register_11;
  wire gpio_dataout_register_11_D_IN, gpio_dataout_register_11_EN;

  // register gpio_dataout_register_12
  reg gpio_dataout_register_12;
  wire gpio_dataout_register_12_D_IN, gpio_dataout_register_12_EN;

  // register gpio_dataout_register_13
  reg gpio_dataout_register_13;
  wire gpio_dataout_register_13_D_IN, gpio_dataout_register_13_EN;

  // register gpio_dataout_register_14
  reg gpio_dataout_register_14;
  wire gpio_dataout_register_14_D_IN, gpio_dataout_register_14_EN;

  // register gpio_dataout_register_15
  reg gpio_dataout_register_15;
  wire gpio_dataout_register_15_D_IN, gpio_dataout_register_15_EN;

  // register gpio_dataout_register_2
  reg gpio_dataout_register_2;
  wire gpio_dataout_register_2_D_IN, gpio_dataout_register_2_EN;

  // register gpio_dataout_register_3
  reg gpio_dataout_register_3;
  wire gpio_dataout_register_3_D_IN, gpio_dataout_register_3_EN;

  // register gpio_dataout_register_4
  reg gpio_dataout_register_4;
  wire gpio_dataout_register_4_D_IN, gpio_dataout_register_4_EN;

  // register gpio_dataout_register_5
  reg gpio_dataout_register_5;
  wire gpio_dataout_register_5_D_IN, gpio_dataout_register_5_EN;

  // register gpio_dataout_register_6
  reg gpio_dataout_register_6;
  wire gpio_dataout_register_6_D_IN, gpio_dataout_register_6_EN;

  // register gpio_dataout_register_7
  reg gpio_dataout_register_7;
  wire gpio_dataout_register_7_D_IN, gpio_dataout_register_7_EN;

  // register gpio_dataout_register_8
  reg gpio_dataout_register_8;
  wire gpio_dataout_register_8_D_IN, gpio_dataout_register_8_EN;

  // register gpio_dataout_register_9
  reg gpio_dataout_register_9;
  wire gpio_dataout_register_9_D_IN, gpio_dataout_register_9_EN;

  // register gpio_direction_reg_0
  reg gpio_direction_reg_0;
  wire gpio_direction_reg_0_D_IN, gpio_direction_reg_0_EN;

  // register gpio_direction_reg_1
  reg gpio_direction_reg_1;
  wire gpio_direction_reg_1_D_IN, gpio_direction_reg_1_EN;

  // register gpio_direction_reg_10
  reg gpio_direction_reg_10;
  wire gpio_direction_reg_10_D_IN, gpio_direction_reg_10_EN;

  // register gpio_direction_reg_11
  reg gpio_direction_reg_11;
  wire gpio_direction_reg_11_D_IN, gpio_direction_reg_11_EN;

  // register gpio_direction_reg_12
  reg gpio_direction_reg_12;
  wire gpio_direction_reg_12_D_IN, gpio_direction_reg_12_EN;

  // register gpio_direction_reg_13
  reg gpio_direction_reg_13;
  wire gpio_direction_reg_13_D_IN, gpio_direction_reg_13_EN;

  // register gpio_direction_reg_14
  reg gpio_direction_reg_14;
  wire gpio_direction_reg_14_D_IN, gpio_direction_reg_14_EN;

  // register gpio_direction_reg_15
  reg gpio_direction_reg_15;
  wire gpio_direction_reg_15_D_IN, gpio_direction_reg_15_EN;

  // register gpio_direction_reg_2
  reg gpio_direction_reg_2;
  wire gpio_direction_reg_2_D_IN, gpio_direction_reg_2_EN;

  // register gpio_direction_reg_3
  reg gpio_direction_reg_3;
  wire gpio_direction_reg_3_D_IN, gpio_direction_reg_3_EN;

  // register gpio_direction_reg_4
  reg gpio_direction_reg_4;
  wire gpio_direction_reg_4_D_IN, gpio_direction_reg_4_EN;

  // register gpio_direction_reg_5
  reg gpio_direction_reg_5;
  wire gpio_direction_reg_5_D_IN, gpio_direction_reg_5_EN;

  // register gpio_direction_reg_6
  reg gpio_direction_reg_6;
  wire gpio_direction_reg_6_D_IN, gpio_direction_reg_6_EN;

  // register gpio_direction_reg_7
  reg gpio_direction_reg_7;
  wire gpio_direction_reg_7_D_IN, gpio_direction_reg_7_EN;

  // register gpio_direction_reg_8
  reg gpio_direction_reg_8;
  wire gpio_direction_reg_8_D_IN, gpio_direction_reg_8_EN;

  // register gpio_direction_reg_9
  reg gpio_direction_reg_9;
  wire gpio_direction_reg_9_D_IN, gpio_direction_reg_9_EN;

  // register gpio_toplic_0
  reg gpio_toplic_0;
  wire gpio_toplic_0_D_IN, gpio_toplic_0_EN;

  // register gpio_toplic_1
  reg gpio_toplic_1;
  wire gpio_toplic_1_D_IN, gpio_toplic_1_EN;

  // register gpio_toplic_10
  reg gpio_toplic_10;
  wire gpio_toplic_10_D_IN, gpio_toplic_10_EN;

  // register gpio_toplic_11
  reg gpio_toplic_11;
  wire gpio_toplic_11_D_IN, gpio_toplic_11_EN;

  // register gpio_toplic_12
  reg gpio_toplic_12;
  wire gpio_toplic_12_D_IN, gpio_toplic_12_EN;

  // register gpio_toplic_13
  reg gpio_toplic_13;
  wire gpio_toplic_13_D_IN, gpio_toplic_13_EN;

  // register gpio_toplic_14
  reg gpio_toplic_14;
  wire gpio_toplic_14_D_IN, gpio_toplic_14_EN;

  // register gpio_toplic_15
  reg gpio_toplic_15;
  wire gpio_toplic_15_D_IN, gpio_toplic_15_EN;

  // register gpio_toplic_2
  reg gpio_toplic_2;
  wire gpio_toplic_2_D_IN, gpio_toplic_2_EN;

  // register gpio_toplic_3
  reg gpio_toplic_3;
  wire gpio_toplic_3_D_IN, gpio_toplic_3_EN;

  // register gpio_toplic_4
  reg gpio_toplic_4;
  wire gpio_toplic_4_D_IN, gpio_toplic_4_EN;

  // register gpio_toplic_5
  reg gpio_toplic_5;
  wire gpio_toplic_5_D_IN, gpio_toplic_5_EN;

  // register gpio_toplic_6
  reg gpio_toplic_6;
  wire gpio_toplic_6_D_IN, gpio_toplic_6_EN;

  // register gpio_toplic_7
  reg gpio_toplic_7;
  wire gpio_toplic_7_D_IN, gpio_toplic_7_EN;

  // register gpio_toplic_8
  reg gpio_toplic_8;
  wire gpio_toplic_8_D_IN, gpio_toplic_8_EN;

  // register gpio_toplic_9
  reg gpio_toplic_9;
  wire gpio_toplic_9_D_IN, gpio_toplic_9_EN;

  // ports of submodule s_xactor_f_rd_addr
  wire [36 : 0] s_xactor_f_rd_addr_D_IN, s_xactor_f_rd_addr_D_OUT;
  wire s_xactor_f_rd_addr_CLR,
       s_xactor_f_rd_addr_DEQ,
       s_xactor_f_rd_addr_EMPTY_N,
       s_xactor_f_rd_addr_ENQ,
       s_xactor_f_rd_addr_FULL_N;

  // ports of submodule s_xactor_f_rd_data
  wire [33 : 0] s_xactor_f_rd_data_D_IN, s_xactor_f_rd_data_D_OUT;
  wire s_xactor_f_rd_data_CLR,
       s_xactor_f_rd_data_DEQ,
       s_xactor_f_rd_data_EMPTY_N,
       s_xactor_f_rd_data_ENQ,
       s_xactor_f_rd_data_FULL_N;

  // ports of submodule s_xactor_f_wr_addr
  wire [36 : 0] s_xactor_f_wr_addr_D_IN, s_xactor_f_wr_addr_D_OUT;
  wire s_xactor_f_wr_addr_CLR,
       s_xactor_f_wr_addr_DEQ,
       s_xactor_f_wr_addr_EMPTY_N,
       s_xactor_f_wr_addr_ENQ,
       s_xactor_f_wr_addr_FULL_N;

  // ports of submodule s_xactor_f_wr_data
  wire [35 : 0] s_xactor_f_wr_data_D_IN, s_xactor_f_wr_data_D_OUT;
  wire s_xactor_f_wr_data_CLR,
       s_xactor_f_wr_data_DEQ,
       s_xactor_f_wr_data_EMPTY_N,
       s_xactor_f_wr_data_ENQ,
       s_xactor_f_wr_data_FULL_N;

  // ports of submodule s_xactor_f_wr_resp
  wire [1 : 0] s_xactor_f_wr_resp_D_IN, s_xactor_f_wr_resp_D_OUT;
  wire s_xactor_f_wr_resp_CLR,
       s_xactor_f_wr_resp_DEQ,
       s_xactor_f_wr_resp_EMPTY_N,
       s_xactor_f_wr_resp_ENQ,
       s_xactor_f_wr_resp_FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_gpio_capture_interrupt,
       CAN_FIRE_RL_read_request,
       CAN_FIRE_RL_write_request,
       CAN_FIRE_io_gpio_in,
       CAN_FIRE_sb_gpio_to_plic_get,
       CAN_FIRE_slave_m_arvalid,
       CAN_FIRE_slave_m_awvalid,
       CAN_FIRE_slave_m_bready,
       CAN_FIRE_slave_m_rready,
       CAN_FIRE_slave_m_wvalid,
       WILL_FIRE_RL_gpio_capture_interrupt,
       WILL_FIRE_RL_read_request,
       WILL_FIRE_RL_write_request,
       WILL_FIRE_io_gpio_in,
       WILL_FIRE_sb_gpio_to_plic_get,
       WILL_FIRE_slave_m_arvalid,
       WILL_FIRE_slave_m_awvalid,
       WILL_FIRE_slave_m_bready,
       WILL_FIRE_slave_m_rready,
       WILL_FIRE_slave_m_wvalid;

  // remaining internal signals
  reg [63 : 0] mask__h7111, x__h10167;
  wire [63 : 0] IF_gpio_datain_register_0_read_THEN_1_ELSE_0___d133,
		IF_gpio_direction_reg_0_read_THEN_1_ELSE_0___d120,
		_0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86,
		_theResult_____2__h10003,
		_theResult___snd__h10096,
		_theResult___snd__h10162,
		mask__h7113,
		temp___1__h10610,
		temp__h10002,
		temp__h10181,
		temp__h13581;
  wire [5 : 0] shift_amt__h7112, shift_amt__h9999;
  wire s_xactor_f_rd_addr_first__11_BITS_11_TO_5_12_U_ETC___d113,
       s_xactor_f_rd_addr_first__11_BITS_11_TO_5_12_U_ETC___d114,
       s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104,
       s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72;

  // action method slave_m_awvalid
  assign CAN_FIRE_slave_m_awvalid = 1'd1 ;
  assign WILL_FIRE_slave_m_awvalid = 1'd1 ;

  // value method slave_m_awready
  assign slave_awready = s_xactor_f_wr_addr_FULL_N ;

  // action method slave_m_wvalid
  assign CAN_FIRE_slave_m_wvalid = 1'd1 ;
  assign WILL_FIRE_slave_m_wvalid = 1'd1 ;

  // value method slave_m_wready
  assign slave_wready = s_xactor_f_wr_data_FULL_N ;

  // value method slave_m_bvalid
  assign slave_bvalid = s_xactor_f_wr_resp_EMPTY_N ;

  // value method slave_m_bresp
  assign slave_bresp = s_xactor_f_wr_resp_D_OUT ;

  // action method slave_m_bready
  assign CAN_FIRE_slave_m_bready = 1'd1 ;
  assign WILL_FIRE_slave_m_bready = 1'd1 ;

  // action method slave_m_arvalid
  assign CAN_FIRE_slave_m_arvalid = 1'd1 ;
  assign WILL_FIRE_slave_m_arvalid = 1'd1 ;

  // value method slave_m_arready
  assign slave_arready = s_xactor_f_rd_addr_FULL_N ;

  // value method slave_m_rvalid
  assign slave_rvalid = s_xactor_f_rd_data_EMPTY_N ;

  // value method slave_m_rresp
  assign slave_rresp = s_xactor_f_rd_data_D_OUT[33:32] ;

  // value method slave_m_rdata
  assign slave_rdata = s_xactor_f_rd_data_D_OUT[31:0] ;

  // action method slave_m_rready
  assign CAN_FIRE_slave_m_rready = 1'd1 ;
  assign WILL_FIRE_slave_m_rready = 1'd1 ;

  // actionvalue method sb_gpio_to_plic_get
  assign sb_gpio_to_plic_get =
	     { gpio_toplic_15,
	       gpio_toplic_14,
	       gpio_toplic_13,
	       gpio_toplic_12,
	       gpio_toplic_11,
	       gpio_toplic_10,
	       gpio_toplic_9,
	       gpio_toplic_8,
	       gpio_toplic_7,
	       gpio_toplic_6,
	       gpio_toplic_5,
	       gpio_toplic_4,
	       gpio_toplic_3,
	       gpio_toplic_2,
	       gpio_toplic_1,
	       gpio_toplic_0 } ;
  assign CAN_FIRE_sb_gpio_to_plic_get = 1'd1 ;
  assign WILL_FIRE_sb_gpio_to_plic_get = 1'd1 ;

  // action method io_gpio_in
  assign CAN_FIRE_io_gpio_in = 1'd1 ;
  assign WILL_FIRE_io_gpio_in = 1'd1 ;

  // value method io_gpio_out
  assign io_gpio_out =
	     { gpio_dataout_register_15,
	       gpio_dataout_register_14,
	       gpio_dataout_register_13,
	       gpio_dataout_register_12,
	       gpio_dataout_register_11,
	       gpio_dataout_register_10,
	       gpio_dataout_register_9,
	       gpio_dataout_register_8,
	       gpio_dataout_register_7,
	       gpio_dataout_register_6,
	       gpio_dataout_register_5,
	       gpio_dataout_register_4,
	       gpio_dataout_register_3,
	       gpio_dataout_register_2,
	       gpio_dataout_register_1,
	       gpio_dataout_register_0 } ;
  assign RDY_io_gpio_out = 1'd1 ;

  // value method io_gpio_out_en
  assign io_gpio_out_en =
	     { gpio_direction_reg_15,
	       gpio_direction_reg_14,
	       gpio_direction_reg_13,
	       gpio_direction_reg_12,
	       gpio_direction_reg_11,
	       gpio_direction_reg_10,
	       gpio_direction_reg_9,
	       gpio_direction_reg_8,
	       gpio_direction_reg_7,
	       gpio_direction_reg_6,
	       gpio_direction_reg_5,
	       gpio_direction_reg_4,
	       gpio_direction_reg_3,
	       gpio_direction_reg_2,
	       gpio_direction_reg_1,
	       gpio_direction_reg_0 } ;
  assign RDY_io_gpio_out_en = 1'd1 ;

  // submodule s_xactor_f_rd_addr
  FIFO2 #(.width(32'd37), .guarded(1'd1)) s_xactor_f_rd_addr(.RST(RST_N),
							     .CLK(CLK),
							     .D_IN(s_xactor_f_rd_addr_D_IN),
							     .ENQ(s_xactor_f_rd_addr_ENQ),
							     .DEQ(s_xactor_f_rd_addr_DEQ),
							     .CLR(s_xactor_f_rd_addr_CLR),
							     .D_OUT(s_xactor_f_rd_addr_D_OUT),
							     .FULL_N(s_xactor_f_rd_addr_FULL_N),
							     .EMPTY_N(s_xactor_f_rd_addr_EMPTY_N));

  // submodule s_xactor_f_rd_data
  FIFO2 #(.width(32'd34), .guarded(1'd1)) s_xactor_f_rd_data(.RST(RST_N),
							     .CLK(CLK),
							     .D_IN(s_xactor_f_rd_data_D_IN),
							     .ENQ(s_xactor_f_rd_data_ENQ),
							     .DEQ(s_xactor_f_rd_data_DEQ),
							     .CLR(s_xactor_f_rd_data_CLR),
							     .D_OUT(s_xactor_f_rd_data_D_OUT),
							     .FULL_N(s_xactor_f_rd_data_FULL_N),
							     .EMPTY_N(s_xactor_f_rd_data_EMPTY_N));

  // submodule s_xactor_f_wr_addr
  FIFO2 #(.width(32'd37), .guarded(1'd1)) s_xactor_f_wr_addr(.RST(RST_N),
							     .CLK(CLK),
							     .D_IN(s_xactor_f_wr_addr_D_IN),
							     .ENQ(s_xactor_f_wr_addr_ENQ),
							     .DEQ(s_xactor_f_wr_addr_DEQ),
							     .CLR(s_xactor_f_wr_addr_CLR),
							     .D_OUT(s_xactor_f_wr_addr_D_OUT),
							     .FULL_N(s_xactor_f_wr_addr_FULL_N),
							     .EMPTY_N(s_xactor_f_wr_addr_EMPTY_N));

  // submodule s_xactor_f_wr_data
  FIFO2 #(.width(32'd36), .guarded(1'd1)) s_xactor_f_wr_data(.RST(RST_N),
							     .CLK(CLK),
							     .D_IN(s_xactor_f_wr_data_D_IN),
							     .ENQ(s_xactor_f_wr_data_ENQ),
							     .DEQ(s_xactor_f_wr_data_DEQ),
							     .CLR(s_xactor_f_wr_data_CLR),
							     .D_OUT(s_xactor_f_wr_data_D_OUT),
							     .FULL_N(s_xactor_f_wr_data_FULL_N),
							     .EMPTY_N(s_xactor_f_wr_data_EMPTY_N));

  // submodule s_xactor_f_wr_resp
  FIFO2 #(.width(32'd2), .guarded(1'd1)) s_xactor_f_wr_resp(.RST(RST_N),
							    .CLK(CLK),
							    .D_IN(s_xactor_f_wr_resp_D_IN),
							    .ENQ(s_xactor_f_wr_resp_ENQ),
							    .DEQ(s_xactor_f_wr_resp_DEQ),
							    .CLR(s_xactor_f_wr_resp_CLR),
							    .D_OUT(s_xactor_f_wr_resp_D_OUT),
							    .FULL_N(s_xactor_f_wr_resp_FULL_N),
							    .EMPTY_N(s_xactor_f_wr_resp_EMPTY_N));

  // rule RL_write_request
  assign CAN_FIRE_RL_write_request =
	     s_xactor_f_wr_addr_EMPTY_N && s_xactor_f_wr_data_EMPTY_N &&
	     s_xactor_f_wr_resp_FULL_N ;
  assign WILL_FIRE_RL_write_request = CAN_FIRE_RL_write_request ;

  // rule RL_read_request
  assign CAN_FIRE_RL_read_request =
	     s_xactor_f_rd_addr_EMPTY_N && s_xactor_f_rd_data_FULL_N ;
  assign WILL_FIRE_RL_read_request = CAN_FIRE_RL_read_request ;

  // rule RL_gpio_capture_interrupt
  assign CAN_FIRE_RL_gpio_capture_interrupt = 1'd1 ;
  assign WILL_FIRE_RL_gpio_capture_interrupt = 1'd1 ;

  // register gpio_datain_register_0
  assign gpio_datain_register_0_D_IN = io_gpio_in_inp[0] ;
  assign gpio_datain_register_0_EN = 1'd1 ;

  // register gpio_datain_register_1
  assign gpio_datain_register_1_D_IN = io_gpio_in_inp[1] ;
  assign gpio_datain_register_1_EN = 1'd1 ;

  // register gpio_datain_register_10
  assign gpio_datain_register_10_D_IN = io_gpio_in_inp[10] ;
  assign gpio_datain_register_10_EN = 1'd1 ;

  // register gpio_datain_register_11
  assign gpio_datain_register_11_D_IN = io_gpio_in_inp[11] ;
  assign gpio_datain_register_11_EN = 1'd1 ;

  // register gpio_datain_register_12
  assign gpio_datain_register_12_D_IN = io_gpio_in_inp[12] ;
  assign gpio_datain_register_12_EN = 1'd1 ;

  // register gpio_datain_register_13
  assign gpio_datain_register_13_D_IN = io_gpio_in_inp[13] ;
  assign gpio_datain_register_13_EN = 1'd1 ;

  // register gpio_datain_register_14
  assign gpio_datain_register_14_D_IN = io_gpio_in_inp[14] ;
  assign gpio_datain_register_14_EN = 1'd1 ;

  // register gpio_datain_register_15
  assign gpio_datain_register_15_D_IN = io_gpio_in_inp[15] ;
  assign gpio_datain_register_15_EN = 1'd1 ;

  // register gpio_datain_register_2
  assign gpio_datain_register_2_D_IN = io_gpio_in_inp[2] ;
  assign gpio_datain_register_2_EN = 1'd1 ;

  // register gpio_datain_register_3
  assign gpio_datain_register_3_D_IN = io_gpio_in_inp[3] ;
  assign gpio_datain_register_3_EN = 1'd1 ;

  // register gpio_datain_register_4
  assign gpio_datain_register_4_D_IN = io_gpio_in_inp[4] ;
  assign gpio_datain_register_4_EN = 1'd1 ;

  // register gpio_datain_register_5
  assign gpio_datain_register_5_D_IN = io_gpio_in_inp[5] ;
  assign gpio_datain_register_5_EN = 1'd1 ;

  // register gpio_datain_register_6
  assign gpio_datain_register_6_D_IN = io_gpio_in_inp[6] ;
  assign gpio_datain_register_6_EN = 1'd1 ;

  // register gpio_datain_register_7
  assign gpio_datain_register_7_D_IN = io_gpio_in_inp[7] ;
  assign gpio_datain_register_7_EN = 1'd1 ;

  // register gpio_datain_register_8
  assign gpio_datain_register_8_D_IN = io_gpio_in_inp[8] ;
  assign gpio_datain_register_8_EN = 1'd1 ;

  // register gpio_datain_register_9
  assign gpio_datain_register_9_D_IN = io_gpio_in_inp[9] ;
  assign gpio_datain_register_9_EN = 1'd1 ;

  // register gpio_dataout_register_0
  assign gpio_dataout_register_0_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[0] ;
  assign gpio_dataout_register_0_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_1
  assign gpio_dataout_register_1_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[1] ;
  assign gpio_dataout_register_1_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_10
  assign gpio_dataout_register_10_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[10] ;
  assign gpio_dataout_register_10_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_11
  assign gpio_dataout_register_11_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[11] ;
  assign gpio_dataout_register_11_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_12
  assign gpio_dataout_register_12_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[12] ;
  assign gpio_dataout_register_12_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_13
  assign gpio_dataout_register_13_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[13] ;
  assign gpio_dataout_register_13_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_14
  assign gpio_dataout_register_14_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[14] ;
  assign gpio_dataout_register_14_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_15
  assign gpio_dataout_register_15_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[15] ;
  assign gpio_dataout_register_15_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_2
  assign gpio_dataout_register_2_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[2] ;
  assign gpio_dataout_register_2_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_3
  assign gpio_dataout_register_3_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[3] ;
  assign gpio_dataout_register_3_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_4
  assign gpio_dataout_register_4_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[4] ;
  assign gpio_dataout_register_4_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_5
  assign gpio_dataout_register_5_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[5] ;
  assign gpio_dataout_register_5_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_6
  assign gpio_dataout_register_6_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[6] ;
  assign gpio_dataout_register_6_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_7
  assign gpio_dataout_register_7_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[7] ;
  assign gpio_dataout_register_7_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_8
  assign gpio_dataout_register_8_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[8] ;
  assign gpio_dataout_register_8_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_dataout_register_9
  assign gpio_dataout_register_9_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[9] ;
  assign gpio_dataout_register_9_EN =
	     WILL_FIRE_RL_write_request &&
	     !s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 ;

  // register gpio_direction_reg_0
  assign gpio_direction_reg_0_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[0] ;
  assign gpio_direction_reg_0_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_1
  assign gpio_direction_reg_1_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[1] ;
  assign gpio_direction_reg_1_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_10
  assign gpio_direction_reg_10_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[10] ;
  assign gpio_direction_reg_10_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_11
  assign gpio_direction_reg_11_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[11] ;
  assign gpio_direction_reg_11_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_12
  assign gpio_direction_reg_12_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[12] ;
  assign gpio_direction_reg_12_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_13
  assign gpio_direction_reg_13_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[13] ;
  assign gpio_direction_reg_13_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_14
  assign gpio_direction_reg_14_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[14] ;
  assign gpio_direction_reg_14_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_15
  assign gpio_direction_reg_15_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[15] ;
  assign gpio_direction_reg_15_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_2
  assign gpio_direction_reg_2_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[2] ;
  assign gpio_direction_reg_2_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_3
  assign gpio_direction_reg_3_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[3] ;
  assign gpio_direction_reg_3_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_4
  assign gpio_direction_reg_4_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[4] ;
  assign gpio_direction_reg_4_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_5
  assign gpio_direction_reg_5_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[5] ;
  assign gpio_direction_reg_5_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_6
  assign gpio_direction_reg_6_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[6] ;
  assign gpio_direction_reg_6_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_7
  assign gpio_direction_reg_7_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[7] ;
  assign gpio_direction_reg_7_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_8
  assign gpio_direction_reg_8_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[8] ;
  assign gpio_direction_reg_8_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_direction_reg_9
  assign gpio_direction_reg_9_D_IN =
	     _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86[9] ;
  assign gpio_direction_reg_9_EN =
	     WILL_FIRE_RL_write_request &&
	     s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ;

  // register gpio_toplic_0
  assign gpio_toplic_0_D_IN =
	     !gpio_direction_reg_0 && gpio_datain_register_0 ;
  assign gpio_toplic_0_EN = 1'd1 ;

  // register gpio_toplic_1
  assign gpio_toplic_1_D_IN =
	     !gpio_direction_reg_1 && gpio_datain_register_1 ;
  assign gpio_toplic_1_EN = 1'd1 ;

  // register gpio_toplic_10
  assign gpio_toplic_10_D_IN =
	     !gpio_direction_reg_10 && gpio_datain_register_10 ;
  assign gpio_toplic_10_EN = 1'd1 ;

  // register gpio_toplic_11
  assign gpio_toplic_11_D_IN =
	     !gpio_direction_reg_11 && gpio_datain_register_11 ;
  assign gpio_toplic_11_EN = 1'd1 ;

  // register gpio_toplic_12
  assign gpio_toplic_12_D_IN =
	     !gpio_direction_reg_12 && gpio_datain_register_12 ;
  assign gpio_toplic_12_EN = 1'd1 ;

  // register gpio_toplic_13
  assign gpio_toplic_13_D_IN =
	     !gpio_direction_reg_13 && gpio_datain_register_13 ;
  assign gpio_toplic_13_EN = 1'd1 ;

  // register gpio_toplic_14
  assign gpio_toplic_14_D_IN =
	     !gpio_direction_reg_14 && gpio_datain_register_14 ;
  assign gpio_toplic_14_EN = 1'd1 ;

  // register gpio_toplic_15
  assign gpio_toplic_15_D_IN =
	     !gpio_direction_reg_15 && gpio_datain_register_15 ;
  assign gpio_toplic_15_EN = 1'd1 ;

  // register gpio_toplic_2
  assign gpio_toplic_2_D_IN =
	     !gpio_direction_reg_2 && gpio_datain_register_2 ;
  assign gpio_toplic_2_EN = 1'd1 ;

  // register gpio_toplic_3
  assign gpio_toplic_3_D_IN =
	     !gpio_direction_reg_3 && gpio_datain_register_3 ;
  assign gpio_toplic_3_EN = 1'd1 ;

  // register gpio_toplic_4
  assign gpio_toplic_4_D_IN =
	     !gpio_direction_reg_4 && gpio_datain_register_4 ;
  assign gpio_toplic_4_EN = 1'd1 ;

  // register gpio_toplic_5
  assign gpio_toplic_5_D_IN =
	     !gpio_direction_reg_5 && gpio_datain_register_5 ;
  assign gpio_toplic_5_EN = 1'd1 ;

  // register gpio_toplic_6
  assign gpio_toplic_6_D_IN =
	     !gpio_direction_reg_6 && gpio_datain_register_6 ;
  assign gpio_toplic_6_EN = 1'd1 ;

  // register gpio_toplic_7
  assign gpio_toplic_7_D_IN =
	     !gpio_direction_reg_7 && gpio_datain_register_7 ;
  assign gpio_toplic_7_EN = 1'd1 ;

  // register gpio_toplic_8
  assign gpio_toplic_8_D_IN =
	     !gpio_direction_reg_8 && gpio_datain_register_8 ;
  assign gpio_toplic_8_EN = 1'd1 ;

  // register gpio_toplic_9
  assign gpio_toplic_9_D_IN =
	     !gpio_direction_reg_9 && gpio_datain_register_9 ;
  assign gpio_toplic_9_EN = 1'd1 ;

  // submodule s_xactor_f_rd_addr
  assign s_xactor_f_rd_addr_D_IN =
	     { slave_m_arvalid_araddr,
	       slave_m_arvalid_arprot,
	       slave_m_arvalid_arsize } ;
  assign s_xactor_f_rd_addr_ENQ =
	     slave_m_arvalid_arvalid && s_xactor_f_rd_addr_FULL_N ;
  assign s_xactor_f_rd_addr_DEQ =
	     s_xactor_f_rd_addr_EMPTY_N && s_xactor_f_rd_data_FULL_N ;
  assign s_xactor_f_rd_addr_CLR = 1'b0 ;

  // submodule s_xactor_f_rd_data
  assign s_xactor_f_rd_data_D_IN =
	     { (s_xactor_f_rd_addr_first__11_BITS_11_TO_5_12_U_ETC___d113 ||
		s_xactor_f_rd_addr_first__11_BITS_11_TO_5_12_U_ETC___d114) ?
		 2'd0 :
		 2'd2,
	       x__h10167[31:0] } ;
  assign s_xactor_f_rd_data_ENQ =
	     s_xactor_f_rd_addr_EMPTY_N && s_xactor_f_rd_data_FULL_N ;
  assign s_xactor_f_rd_data_DEQ =
	     slave_m_rready_rready && s_xactor_f_rd_data_EMPTY_N ;
  assign s_xactor_f_rd_data_CLR = 1'b0 ;

  // submodule s_xactor_f_wr_addr
  assign s_xactor_f_wr_addr_D_IN =
	     { slave_m_awvalid_awaddr,
	       slave_m_awvalid_awprot,
	       slave_m_awvalid_awsize } ;
  assign s_xactor_f_wr_addr_ENQ =
	     slave_m_awvalid_awvalid && s_xactor_f_wr_addr_FULL_N ;
  assign s_xactor_f_wr_addr_DEQ =
	     s_xactor_f_wr_addr_EMPTY_N && s_xactor_f_wr_data_EMPTY_N &&
	     s_xactor_f_wr_resp_FULL_N ;
  assign s_xactor_f_wr_addr_CLR = 1'b0 ;

  // submodule s_xactor_f_wr_data
  assign s_xactor_f_wr_data_D_IN =
	     { slave_m_wvalid_wdata, slave_m_wvalid_wstrb } ;
  assign s_xactor_f_wr_data_ENQ =
	     slave_m_wvalid_wvalid && s_xactor_f_wr_data_FULL_N ;
  assign s_xactor_f_wr_data_DEQ =
	     s_xactor_f_wr_addr_EMPTY_N && s_xactor_f_wr_data_EMPTY_N &&
	     s_xactor_f_wr_resp_FULL_N ;
  assign s_xactor_f_wr_data_CLR = 1'b0 ;

  // submodule s_xactor_f_wr_resp
  assign s_xactor_f_wr_resp_D_IN =
	     (s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 ||
	      s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104) ?
	       2'd0 :
	       2'd2 ;
  assign s_xactor_f_wr_resp_ENQ =
	     s_xactor_f_wr_addr_EMPTY_N && s_xactor_f_wr_data_EMPTY_N &&
	     s_xactor_f_wr_resp_FULL_N ;
  assign s_xactor_f_wr_resp_DEQ =
	     slave_m_bready_bready && s_xactor_f_wr_resp_EMPTY_N ;
  assign s_xactor_f_wr_resp_CLR = 1'b0 ;

  // remaining internal signals
  assign IF_gpio_datain_register_0_read_THEN_1_ELSE_0___d133 =
	     gpio_datain_register_0 ? 64'd1 : 64'd0 ;
  assign IF_gpio_direction_reg_0_read_THEN_1_ELSE_0___d120 =
	     gpio_direction_reg_0 ? 64'd1 : 64'd0 ;
  assign _0_CONCAT_s_xactor_f_wr_data_first__3_BITS_35_T_ETC___d86 =
	     { 32'd0, s_xactor_f_wr_data_D_OUT[35:4] } & mask__h7113 ;
  assign _theResult_____2__h10003 =
	     (s_xactor_f_rd_addr_D_OUT[1:0] == 2'd0) ?
	       temp___1__h10610 :
	       temp__h10002 ;
  assign _theResult___snd__h10096 =
	     s_xactor_f_rd_addr_first__11_BITS_11_TO_5_12_U_ETC___d113 ?
	       { IF_gpio_direction_reg_0_read_THEN_1_ELSE_0___d120[63:16],
		 gpio_direction_reg_15,
		 gpio_direction_reg_14,
		 gpio_direction_reg_13,
		 gpio_direction_reg_12,
		 gpio_direction_reg_11,
		 gpio_direction_reg_10,
		 gpio_direction_reg_9,
		 gpio_direction_reg_8,
		 gpio_direction_reg_7,
		 gpio_direction_reg_6,
		 gpio_direction_reg_5,
		 gpio_direction_reg_4,
		 gpio_direction_reg_3,
		 gpio_direction_reg_2,
		 gpio_direction_reg_1,
		 IF_gpio_direction_reg_0_read_THEN_1_ELSE_0___d120[0] } :
	       _theResult___snd__h10162 ;
  assign _theResult___snd__h10162 =
	     (!s_xactor_f_rd_addr_first__11_BITS_11_TO_5_12_U_ETC___d113 &&
	      s_xactor_f_rd_addr_first__11_BITS_11_TO_5_12_U_ETC___d114) ?
	       { IF_gpio_datain_register_0_read_THEN_1_ELSE_0___d133[63:16],
		 gpio_datain_register_15,
		 gpio_datain_register_14,
		 gpio_datain_register_13,
		 gpio_datain_register_12,
		 gpio_datain_register_11,
		 gpio_datain_register_10,
		 gpio_datain_register_9,
		 gpio_datain_register_8,
		 gpio_datain_register_7,
		 gpio_datain_register_6,
		 gpio_datain_register_5,
		 gpio_datain_register_4,
		 gpio_datain_register_3,
		 gpio_datain_register_2,
		 gpio_datain_register_1,
		 IF_gpio_datain_register_0_read_THEN_1_ELSE_0___d133[0] } :
	       64'd0 ;
  assign mask__h7113 = mask__h7111 << shift_amt__h7112 ;
  assign s_xactor_f_rd_addr_first__11_BITS_11_TO_5_12_U_ETC___d113 =
	     s_xactor_f_rd_addr_D_OUT[11:5] < 7'h08 ;
  assign s_xactor_f_rd_addr_first__11_BITS_11_TO_5_12_U_ETC___d114 =
	     s_xactor_f_rd_addr_D_OUT[11:5] < 7'd16 ;
  assign s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_16___d104 =
	     s_xactor_f_wr_addr_D_OUT[11:5] < 7'd16 ;
  assign s_xactor_f_wr_addr_first__0_BITS_11_TO_5_1_ULT_ETC___d72 =
	     s_xactor_f_wr_addr_D_OUT[11:5] < 7'h08 ;
  assign shift_amt__h7112 = { s_xactor_f_wr_addr_D_OUT[7:5], 3'd0 } ;
  assign shift_amt__h9999 = { s_xactor_f_rd_addr_D_OUT[7:5], 3'd0 } ;
  assign temp___1__h10610 = {8{temp__h10002[7:0]}} ;
  assign temp__h10002 = _theResult___snd__h10096 >> shift_amt__h9999 ;
  assign temp__h10181 = {4{_theResult_____2__h10003[15:0]}} ;
  assign temp__h13581 = {2{_theResult_____2__h10003[31:0]}} ;
  always@(s_xactor_f_wr_addr_D_OUT)
  begin
    case (s_xactor_f_wr_addr_D_OUT[1:0])
      2'd0: mask__h7111 = 64'h00000000000000FF;
      2'd1: mask__h7111 = 64'h000000000000FFFF;
      2'd2: mask__h7111 = 64'h00000000FFFFFFFF;
      2'd3: mask__h7111 = 64'hFFFFFFFFFFFFFFFF;
    endcase
  end
  always@(s_xactor_f_rd_addr_D_OUT or
	  temp__h10002 or temp___1__h10610 or temp__h10181 or temp__h13581)
  begin
    case (s_xactor_f_rd_addr_D_OUT[1:0])
      2'd0: x__h10167 = temp___1__h10610;
      2'd1: x__h10167 = temp__h10181;
      2'd2: x__h10167 = temp__h13581;
      2'd3: x__h10167 = temp__h10002;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        gpio_datain_register_0 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_10 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_11 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_12 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_13 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_14 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_15 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_2 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_3 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_4 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_5 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_6 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_7 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_8 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_datain_register_9 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_0 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_10 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_11 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_12 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_13 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_14 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_15 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_2 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_3 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_4 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_5 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_6 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_7 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_8 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_dataout_register_9 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_0 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_10 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_11 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_12 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_13 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_14 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_15 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_2 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_3 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_4 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_5 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_6 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_7 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_8 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_direction_reg_9 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_0 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_10 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_11 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_12 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_13 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_14 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_15 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_2 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_3 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_4 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_5 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_6 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_7 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_8 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gpio_toplic_9 <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (gpio_datain_register_0_EN)
	  gpio_datain_register_0 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_0_D_IN;
	if (gpio_datain_register_1_EN)
	  gpio_datain_register_1 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_1_D_IN;
	if (gpio_datain_register_10_EN)
	  gpio_datain_register_10 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_10_D_IN;
	if (gpio_datain_register_11_EN)
	  gpio_datain_register_11 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_11_D_IN;
	if (gpio_datain_register_12_EN)
	  gpio_datain_register_12 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_12_D_IN;
	if (gpio_datain_register_13_EN)
	  gpio_datain_register_13 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_13_D_IN;
	if (gpio_datain_register_14_EN)
	  gpio_datain_register_14 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_14_D_IN;
	if (gpio_datain_register_15_EN)
	  gpio_datain_register_15 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_15_D_IN;
	if (gpio_datain_register_2_EN)
	  gpio_datain_register_2 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_2_D_IN;
	if (gpio_datain_register_3_EN)
	  gpio_datain_register_3 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_3_D_IN;
	if (gpio_datain_register_4_EN)
	  gpio_datain_register_4 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_4_D_IN;
	if (gpio_datain_register_5_EN)
	  gpio_datain_register_5 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_5_D_IN;
	if (gpio_datain_register_6_EN)
	  gpio_datain_register_6 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_6_D_IN;
	if (gpio_datain_register_7_EN)
	  gpio_datain_register_7 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_7_D_IN;
	if (gpio_datain_register_8_EN)
	  gpio_datain_register_8 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_8_D_IN;
	if (gpio_datain_register_9_EN)
	  gpio_datain_register_9 <= `BSV_ASSIGNMENT_DELAY
	      gpio_datain_register_9_D_IN;
	if (gpio_dataout_register_0_EN)
	  gpio_dataout_register_0 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_0_D_IN;
	if (gpio_dataout_register_1_EN)
	  gpio_dataout_register_1 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_1_D_IN;
	if (gpio_dataout_register_10_EN)
	  gpio_dataout_register_10 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_10_D_IN;
	if (gpio_dataout_register_11_EN)
	  gpio_dataout_register_11 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_11_D_IN;
	if (gpio_dataout_register_12_EN)
	  gpio_dataout_register_12 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_12_D_IN;
	if (gpio_dataout_register_13_EN)
	  gpio_dataout_register_13 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_13_D_IN;
	if (gpio_dataout_register_14_EN)
	  gpio_dataout_register_14 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_14_D_IN;
	if (gpio_dataout_register_15_EN)
	  gpio_dataout_register_15 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_15_D_IN;
	if (gpio_dataout_register_2_EN)
	  gpio_dataout_register_2 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_2_D_IN;
	if (gpio_dataout_register_3_EN)
	  gpio_dataout_register_3 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_3_D_IN;
	if (gpio_dataout_register_4_EN)
	  gpio_dataout_register_4 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_4_D_IN;
	if (gpio_dataout_register_5_EN)
	  gpio_dataout_register_5 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_5_D_IN;
	if (gpio_dataout_register_6_EN)
	  gpio_dataout_register_6 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_6_D_IN;
	if (gpio_dataout_register_7_EN)
	  gpio_dataout_register_7 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_7_D_IN;
	if (gpio_dataout_register_8_EN)
	  gpio_dataout_register_8 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_8_D_IN;
	if (gpio_dataout_register_9_EN)
	  gpio_dataout_register_9 <= `BSV_ASSIGNMENT_DELAY
	      gpio_dataout_register_9_D_IN;
	if (gpio_direction_reg_0_EN)
	  gpio_direction_reg_0 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_0_D_IN;
	if (gpio_direction_reg_1_EN)
	  gpio_direction_reg_1 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_1_D_IN;
	if (gpio_direction_reg_10_EN)
	  gpio_direction_reg_10 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_10_D_IN;
	if (gpio_direction_reg_11_EN)
	  gpio_direction_reg_11 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_11_D_IN;
	if (gpio_direction_reg_12_EN)
	  gpio_direction_reg_12 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_12_D_IN;
	if (gpio_direction_reg_13_EN)
	  gpio_direction_reg_13 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_13_D_IN;
	if (gpio_direction_reg_14_EN)
	  gpio_direction_reg_14 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_14_D_IN;
	if (gpio_direction_reg_15_EN)
	  gpio_direction_reg_15 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_15_D_IN;
	if (gpio_direction_reg_2_EN)
	  gpio_direction_reg_2 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_2_D_IN;
	if (gpio_direction_reg_3_EN)
	  gpio_direction_reg_3 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_3_D_IN;
	if (gpio_direction_reg_4_EN)
	  gpio_direction_reg_4 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_4_D_IN;
	if (gpio_direction_reg_5_EN)
	  gpio_direction_reg_5 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_5_D_IN;
	if (gpio_direction_reg_6_EN)
	  gpio_direction_reg_6 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_6_D_IN;
	if (gpio_direction_reg_7_EN)
	  gpio_direction_reg_7 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_7_D_IN;
	if (gpio_direction_reg_8_EN)
	  gpio_direction_reg_8 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_8_D_IN;
	if (gpio_direction_reg_9_EN)
	  gpio_direction_reg_9 <= `BSV_ASSIGNMENT_DELAY
	      gpio_direction_reg_9_D_IN;
	if (gpio_toplic_0_EN)
	  gpio_toplic_0 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_0_D_IN;
	if (gpio_toplic_1_EN)
	  gpio_toplic_1 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_1_D_IN;
	if (gpio_toplic_10_EN)
	  gpio_toplic_10 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_10_D_IN;
	if (gpio_toplic_11_EN)
	  gpio_toplic_11 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_11_D_IN;
	if (gpio_toplic_12_EN)
	  gpio_toplic_12 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_12_D_IN;
	if (gpio_toplic_13_EN)
	  gpio_toplic_13 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_13_D_IN;
	if (gpio_toplic_14_EN)
	  gpio_toplic_14 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_14_D_IN;
	if (gpio_toplic_15_EN)
	  gpio_toplic_15 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_15_D_IN;
	if (gpio_toplic_2_EN)
	  gpio_toplic_2 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_2_D_IN;
	if (gpio_toplic_3_EN)
	  gpio_toplic_3 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_3_D_IN;
	if (gpio_toplic_4_EN)
	  gpio_toplic_4 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_4_D_IN;
	if (gpio_toplic_5_EN)
	  gpio_toplic_5 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_5_D_IN;
	if (gpio_toplic_6_EN)
	  gpio_toplic_6 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_6_D_IN;
	if (gpio_toplic_7_EN)
	  gpio_toplic_7 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_7_D_IN;
	if (gpio_toplic_8_EN)
	  gpio_toplic_8 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_8_D_IN;
	if (gpio_toplic_9_EN)
	  gpio_toplic_9 <= `BSV_ASSIGNMENT_DELAY gpio_toplic_9_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    gpio_datain_register_0 = 1'h0;
    gpio_datain_register_1 = 1'h0;
    gpio_datain_register_10 = 1'h0;
    gpio_datain_register_11 = 1'h0;
    gpio_datain_register_12 = 1'h0;
    gpio_datain_register_13 = 1'h0;
    gpio_datain_register_14 = 1'h0;
    gpio_datain_register_15 = 1'h0;
    gpio_datain_register_2 = 1'h0;
    gpio_datain_register_3 = 1'h0;
    gpio_datain_register_4 = 1'h0;
    gpio_datain_register_5 = 1'h0;
    gpio_datain_register_6 = 1'h0;
    gpio_datain_register_7 = 1'h0;
    gpio_datain_register_8 = 1'h0;
    gpio_datain_register_9 = 1'h0;
    gpio_dataout_register_0 = 1'h0;
    gpio_dataout_register_1 = 1'h0;
    gpio_dataout_register_10 = 1'h0;
    gpio_dataout_register_11 = 1'h0;
    gpio_dataout_register_12 = 1'h0;
    gpio_dataout_register_13 = 1'h0;
    gpio_dataout_register_14 = 1'h0;
    gpio_dataout_register_15 = 1'h0;
    gpio_dataout_register_2 = 1'h0;
    gpio_dataout_register_3 = 1'h0;
    gpio_dataout_register_4 = 1'h0;
    gpio_dataout_register_5 = 1'h0;
    gpio_dataout_register_6 = 1'h0;
    gpio_dataout_register_7 = 1'h0;
    gpio_dataout_register_8 = 1'h0;
    gpio_dataout_register_9 = 1'h0;
    gpio_direction_reg_0 = 1'h0;
    gpio_direction_reg_1 = 1'h0;
    gpio_direction_reg_10 = 1'h0;
    gpio_direction_reg_11 = 1'h0;
    gpio_direction_reg_12 = 1'h0;
    gpio_direction_reg_13 = 1'h0;
    gpio_direction_reg_14 = 1'h0;
    gpio_direction_reg_15 = 1'h0;
    gpio_direction_reg_2 = 1'h0;
    gpio_direction_reg_3 = 1'h0;
    gpio_direction_reg_4 = 1'h0;
    gpio_direction_reg_5 = 1'h0;
    gpio_direction_reg_6 = 1'h0;
    gpio_direction_reg_7 = 1'h0;
    gpio_direction_reg_8 = 1'h0;
    gpio_direction_reg_9 = 1'h0;
    gpio_toplic_0 = 1'h0;
    gpio_toplic_1 = 1'h0;
    gpio_toplic_10 = 1'h0;
    gpio_toplic_11 = 1'h0;
    gpio_toplic_12 = 1'h0;
    gpio_toplic_13 = 1'h0;
    gpio_toplic_14 = 1'h0;
    gpio_toplic_15 = 1'h0;
    gpio_toplic_2 = 1'h0;
    gpio_toplic_3 = 1'h0;
    gpio_toplic_4 = 1'h0;
    gpio_toplic_5 = 1'h0;
    gpio_toplic_6 = 1'h0;
    gpio_toplic_7 = 1'h0;
    gpio_toplic_8 = 1'h0;
    gpio_toplic_9 = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkgpio

