//
// Generated by Bluespec Compiler, version 2022.01-36-ga6304315 (build a6304315)
//
// On Tue Oct  4 10:37:05 CEST 2022
//
//
// Ports:
// Name                         I/O  size props
// decoder_func_32                O    62
// decoder_func_32_inst           I    32
// decoder_func_32_csrs           I   118
//
// Combinational paths from inputs to outputs:
//   (decoder_func_32_inst, decoder_func_32_csrs) -> decoder_func_32
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_decoder_func_32(decoder_func_32_inst,
			      decoder_func_32_csrs,
			      decoder_func_32);
  // value method decoder_func_32
  input  [31 : 0] decoder_func_32_inst;
  input  [117 : 0] decoder_func_32_csrs;
  output [61 : 0] decoder_func_32;

  // signals for module outputs
  wire [61 : 0] decoder_func_32;

  // remaining internal signals
  reg [10 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9;
  reg [7 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10;
  reg [5 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7,
	      _theResult_____5_snd__h895,
	      _theResult_____5_snd__h950;
  reg [4 : 0] x__h262;
  reg [3 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8,
	      IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d227,
	      fn___1__h4340,
	      fn___1__h4388;
  reg [2 : 0] CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q2,
	      CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q1,
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q3,
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q6,
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_d_ETC__q5,
	      IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d143;
  reg [1 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b0_1_0b_ETC__q11,
	      CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_3_0_ETC__q12;
  reg CASE_decoder_func_32_inst_BITS_14_TO_12_0_deco_ETC__q4;
  wire [31 : 0] immediate_value___1__h1465,
		immediate_value__h49,
		instr_meta_immediate__h343;
  wire [11 : 0] IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d174;
  wire [10 : 0] bit20_30__h47;
  wire [7 : 0] bit12_19__h46;
  wire [6 : 0] instr_meta_funct__h344, temp1___1__h4157, temp1__h70;
  wire [5 : 0] _theResult_____5_snd__h923, trapcause___1__h945, x__h4160;
  wire [4 : 0] x__h193, x__h20;
  wire [3 : 0] IF_decoder_func_32_inst_BIT_30_16_THEN_0b1011__ETC___d217,
	       fn___1__h4315,
	       fn___1__h4337;
  wire [2 : 0] IF_NOT_decoder_func_32_inst_BITS_1_TO_0_2_EQ_0_ETC___d147,
	       IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_7_ETC___d136;
  wire address_valid___d133;

  // value method decoder_func_32
  assign decoder_func_32 =
	     { x__h20,
	       x__h193,
	       x__h262,
	       decoder_func_32_inst[6:2] == 5'b11011 ||
	       decoder_func_32_inst[6:2] == 5'b11001 ||
	       decoder_func_32_inst[6:2] == 5'b00101,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b0_1_0b_ETC__q11,
	       IF_NOT_decoder_func_32_inst_BITS_1_TO_0_2_EQ_0_ETC___d147,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_3_0_ETC__q12,
	       instr_meta_immediate__h343,
	       instr_meta_funct__h344 } ;

  // remaining internal signals
  module_address_valid instance_address_valid_0(.address_valid_addr(decoder_func_32_inst[31:20]),
						.address_valid_misa(decoder_func_32_csrs[89:64]),
						.address_valid(address_valid___d133));
  assign IF_NOT_decoder_func_32_inst_BITS_1_TO_0_2_EQ_0_ETC___d147 =
	     (decoder_func_32_inst[1:0] != 2'b11 &&
	      IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d143 !=
	      3'd6) ?
	       3'd6 :
	       IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d143 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_7_ETC___d136 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q1 :
	       ((decoder_func_32_inst[14:12] != 3'd4 &&
		 decoder_func_32_csrs[117:116] >=
		 decoder_func_32_inst[29:28] &&
		 (decoder_func_32_inst[19:15] == 5'd0 &&
		  decoder_func_32_inst[13:12] != 2'b01 ||
		  decoder_func_32_inst[31:30] != 2'b11) &&
		 address_valid___d133) ?
		  3'd5 :
		  3'd6) ;
  assign IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d174 =
	     { (decoder_func_32_inst[6:2] == 5'b11000) ?
		 decoder_func_32_inst[7] :
		 decoder_func_32_inst[6:2] != 5'b01101 &&
		 decoder_func_32_inst[6:2] != 5'b00101 &&
		 ((decoder_func_32_inst[6:2] == 5'b11011) ?
		    decoder_func_32_inst[20] :
		    decoder_func_32_inst[31]),
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8,
	       (decoder_func_32_inst[6:2] == 5'b01000) ?
		 decoder_func_32_inst[7] :
		 decoder_func_32_inst[6:2] != 5'b11000 &&
		 decoder_func_32_inst[6:2] != 5'b01101 &&
		 decoder_func_32_inst[6:2] != 5'b00101 &&
		 decoder_func_32_inst[6:2] != 5'b11011 &&
		 decoder_func_32_inst[20] } ;
  assign IF_decoder_func_32_inst_BIT_30_16_THEN_0b1011__ETC___d217 =
	     decoder_func_32_inst[30] ? 4'b1011 : 4'b0101 ;
  assign _theResult_____5_snd__h923 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       _theResult_____5_snd__h950 :
	       6'd2 ;
  assign bit12_19__h46 = {8{decoder_func_32_inst[31]}} ;
  assign bit20_30__h47 =
	     { bit12_19__h46,
	       decoder_func_32_inst[31],
	       decoder_func_32_inst[31],
	       decoder_func_32_inst[31] } ;
  assign fn___1__h4315 = { 3'd1, decoder_func_32_inst[12] } ;
  assign fn___1__h4337 = { 1'b1, decoder_func_32_inst[14:12] } ;
  assign immediate_value___1__h1465 =
	     { 15'd0,
	       decoder_func_32_inst[19:15],
	       IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d174 } ;
  assign immediate_value__h49 =
	     { decoder_func_32_inst[31],
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10,
	       IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d174 } ;
  assign instr_meta_funct__h344 =
	     (IF_NOT_decoder_func_32_inst_BITS_1_TO_0_2_EQ_0_ETC___d147 ==
	      3'd6) ?
	       temp1___1__h4157 :
	       temp1__h70 ;
  assign instr_meta_immediate__h343 =
	     (IF_NOT_decoder_func_32_inst_BITS_1_TO_0_2_EQ_0_ETC___d147 ==
	      3'd5) ?
	       immediate_value___1__h1465 :
	       immediate_value__h49 ;
  assign temp1___1__h4157 = { 1'd0, x__h4160 } ;
  assign temp1__h70 =
	     { IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d227,
	       decoder_func_32_inst[14:12] } ;
  assign trapcause___1__h945 =
	     (decoder_func_32_csrs[84] &&
	      decoder_func_32_csrs[117:116] == 2'd0) ?
	       6'd8 :
	       6'd11 ;
  assign x__h193 =
	     (decoder_func_32_inst[6:2] == 5'b00100 ||
	      decoder_func_32_inst[6:2] == 5'b11100 ||
	      decoder_func_32_inst[6:2] == 5'b01101 ||
	      decoder_func_32_inst[6:2] == 5'b00101 ||
	      decoder_func_32_inst[6:2] == 5'b11011 ||
	      decoder_func_32_inst[6:2] == 5'b11001 ||
	      decoder_func_32_inst[6:4] == 3'b0) ?
	       5'd0 :
	       decoder_func_32_inst[24:20] ;
  assign x__h20 =
	     (decoder_func_32_inst[6:2] == 5'b01101 ||
	      decoder_func_32_inst[6:2] == 5'b00101 ||
	      decoder_func_32_inst[6:2] == 5'b11011 ||
	      decoder_func_32_inst[6:2] == 5'b11100 &&
	      decoder_func_32_inst[14]) ?
	       5'd0 :
	       decoder_func_32_inst[19:15] ;
  assign x__h4160 =
	     (decoder_func_32_inst[1:0] != 2'b11 &&
	      IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d143 !=
	      3'd6 ||
	      decoder_func_32_inst[6:5] == 2'b0 ||
	      decoder_func_32_inst[6:5] == 2'b01) ?
	       6'd2 :
	       ((decoder_func_32_inst[6:5] == 2'b11) ?
		  _theResult_____5_snd__h895 :
		  6'd2) ;
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b01000, 5'b11000: x__h262 = 5'd0;
      default: x__h262 = decoder_func_32_inst[11:7];
    endcase
  end
  always@(decoder_func_32_inst or trapcause___1__h945 or decoder_func_32_csrs)
  begin
    case (decoder_func_32_inst[31:7])
      25'd0: _theResult_____5_snd__h950 = trapcause___1__h945;
      25'h0002000:
	  _theResult_____5_snd__h950 =
	      (decoder_func_32_csrs[15] &&
	       decoder_func_32_csrs[117:116] == 2'd3 ||
	       decoder_func_32_csrs[13] &&
	       decoder_func_32_csrs[117:116] == 2'd0) ?
		6'd49 :
		6'd3;
      default: _theResult_____5_snd__h950 = 6'd2;
    endcase
  end
  always@(decoder_func_32_inst or _theResult_____5_snd__h923)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b011: _theResult_____5_snd__h895 = 6'd2;
      3'b100: _theResult_____5_snd__h895 = _theResult_____5_snd__h923;
      default: _theResult_____5_snd__h895 = 6'd2;
    endcase
  end
  always@(decoder_func_32_inst or decoder_func_32_csrs)
  begin
    case (decoder_func_32_inst[31:7])
      25'd0, 25'h0002000:
	  CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q1 = 3'd6;
      default: CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q1 =
		   (decoder_func_32_inst[31:20] == 12'h002 &&
		    decoder_func_32_inst[19:15] == 5'd0 &&
		    decoder_func_32_inst[11:7] == 5'd0 &&
		    decoder_func_32_csrs[77] ||
		    decoder_func_32_inst[31:20] == 12'h302 &&
		    decoder_func_32_inst[19:15] == 5'd0 &&
		    decoder_func_32_inst[11:7] == 5'd0 &&
		    decoder_func_32_csrs[117:116] == 2'd3) ?
		     3'd5 :
		     ((decoder_func_32_inst[31:20] == 12'h105 &&
		       decoder_func_32_inst[19:15] == 5'd0 &&
		       decoder_func_32_inst[11:7] == 5'd0 &&
		       decoder_func_32_csrs[117:116] == 2'd3) ?
			3'd7 :
			3'd6);
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd1:
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q2 = 3'd1;
      default: CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q2 = 3'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q2)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q3 =
	      (decoder_func_32_inst[14:12] != 3'd3 &&
	       decoder_func_32_inst[14:12] != 3'd7) ?
		3'd1 :
		3'd6;
      3'b011:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q3 =
	      CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q2;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q3 =
	      ((decoder_func_32_inst[14:12] == 3'd1) ?
		 decoder_func_32_inst[31:25] == 7'b0 :
		 decoder_func_32_inst[14:12] != 3'd5 ||
		 decoder_func_32_inst[31:25] == 7'b0 ||
		 decoder_func_32_inst[31:25] == 7'b0100000) ?
		3'd0 :
		3'd6;
      3'b101: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q3 = 3'd0;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q3 = 3'd6;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd5:
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_deco_ETC__q4 =
	      decoder_func_32_inst[31:25] == 7'b0 ||
	      decoder_func_32_inst[31:25] == 7'b0100000;
      default: CASE_decoder_func_32_inst_BITS_14_TO_12_0_deco_ETC__q4 =
		   decoder_func_32_inst[31:25] == 7'b0;
    endcase
  end
  always@(decoder_func_32_inst or
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_deco_ETC__q4)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_d_ETC__q5 =
	      (decoder_func_32_inst[14:12] < 3'd3) ? 3'd1 : 3'd6;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_d_ETC__q5 =
	      CASE_decoder_func_32_inst_BITS_14_TO_12_0_deco_ETC__q4 ?
		3'd0 :
		3'd6;
      3'b101: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_d_ETC__q5 = 3'd0;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_d_ETC__q5 = 3'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_7_ETC___d136)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q6 =
	      (decoder_func_32_inst[14:12] != 3'd2 &&
	       decoder_func_32_inst[14:12] != 3'd3) ?
		3'd2 :
		3'd6;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q6 =
	      (decoder_func_32_inst[14:12] == 3'd0) ? 3'd4 : 3'd6;
      3'b011:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q6 =
	      decoder_func_32_inst[4:2];
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q6 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_9_EQ_0_7_ETC___d136;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q6 = 3'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q3 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_d_ETC__q5 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q6)
  begin
    case (decoder_func_32_inst[6:5])
      2'b0:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d143 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q3;
      2'b01:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d143 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_d_ETC__q5;
      2'd2: IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d143 = 3'd6;
      2'b11:
	  IF_decoder_func_32_inst_BITS_6_TO_5_5_EQ_0b0_6_ETC___d143 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q6;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7 = 6'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7 =
		   decoder_func_32_inst[30:25];
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8 = 4'd0;
      5'b01000, 5'b11000:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8 =
	      decoder_func_32_inst[11:8];
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8 =
		   decoder_func_32_inst[24:21];
    endcase
  end
  always@(decoder_func_32_inst or bit20_30__h47)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9 =
	      decoder_func_32_inst[30:20];
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9 =
		   bit20_30__h47;
    endcase
  end
  always@(decoder_func_32_inst or bit12_19__h46)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101, 5'b11011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10 =
	      decoder_func_32_inst[19:12];
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10 =
		   bit12_19__h46;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BIT_30_16_THEN_0b1011__ETC___d217)
  begin
    case (decoder_func_32_inst[14:12])
      3'd2: fn___1__h4340 = 4'b1100;
      3'd3: fn___1__h4340 = 4'b1110;
      3'd5:
	  fn___1__h4340 =
	      IF_decoder_func_32_inst_BIT_30_16_THEN_0b1011__ETC___d217;
      default: fn___1__h4340 = { 1'b0, decoder_func_32_inst[14:12] };
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BIT_30_16_THEN_0b1011__ETC___d217)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0: fn___1__h4388 = decoder_func_32_inst[30] ? 4'b1010 : 4'b0;
      3'd2: fn___1__h4388 = 4'b1100;
      3'd3: fn___1__h4388 = 4'b1110;
      3'd5:
	  fn___1__h4388 =
	      IF_decoder_func_32_inst_BIT_30_16_THEN_0b1011__ETC___d217;
      default: fn___1__h4388 = { 1'b0, decoder_func_32_inst[14:12] };
    endcase
  end
  always@(decoder_func_32_inst or
	  fn___1__h4340 or fn___1__h4388 or fn___1__h4337 or fn___1__h4315)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00100:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d227 =
	      fn___1__h4340;
      5'b01100:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d227 =
	      fn___1__h4388;
      5'b11000:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d227 =
	      decoder_func_32_inst[14] ? fn___1__h4337 : fn___1__h4315;
      default: IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d227 =
		   4'd0;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b0, 5'b00100, 5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b0_1_0b_ETC__q11 = 2'd1;
      5'b00011, 5'b11001, 5'b11011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b0_1_0b_ETC__q11 = 2'd2;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b0_1_0b_ETC__q11 = 2'd0;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_3_0_ETC__q12 = 2'd3;
      5'b01000:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_3_0_ETC__q12 = 2'd1;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_3_0_ETC__q12 = 2'd0;
    endcase
  end
endmodule  // module_decoder_func_32

